unbind r
bind r source-file ~/.tmux.conf

set -g prefix C-s
set -g mouse on
set -g default-shell /bin/zsh
set -g base-index 1
set -g renumber-windows on

set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",xterm-256color:Tc"

set -g status-style "bg=#89b4fa,fg=black"

# active tab
setw -g window-status-current-format "#[fg=white,bg=#355c7d,bold] #I:#W "

set-window-option -g mode-keys vi

# bind-key h select-pane -L
# bind-key j select-pane -D
# bind-key k select-pane -U
# bind-key l select-pane -R

bind-key -n M-h select-pane -L
bind-key -n M-j select-pane -D
bind-key -n M-k select-pane -U
bind-key -n M-l select-pane -R

unbind -n c-l
unbind c-l

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'dracula/tmux'
# set -g @plugin 'christoomey/vim-tmux-navigator'

set -g @dracula-plugins "ram-usage cpu-usage battery"
set -g @dracula-show-battery-status true
set -g @dracula-show-powerline true
set -g @dracula-show-flags true
set -g @dracula-show-left-icon session
# set -g status-right-length 200
set -g status-position bottom

set -g @dracula-colors "
# simple catppuccin Color Pallette
pink='#cba6f7'
orange='#fab387'
yellow='#f9e2af'
green='#a6e3a1'
cyan='#89dceb'
light_purple='#b4befe'
white='#cdd6f4'
dark_gray='#313244'
red='#f38ba8'
gray='#45475a'
dark_purple='#6c7086'
"

run '~/.tmux/plugins/tpm/tpm'
